language: rust
rust:
  - stable
  - beta
  - nightly
sudo: false
branches:
  only:
    - master
    - devel/2.0.0
    - support/1.x
script:
  - cargo test -- --test-threads=1
  - cargo test --example google
  - cargo test --example github
notifications:
  email:
    on_success: never
