[package]
name = "oauth2"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
version = "0.3.0"
license = "MIT/Apache-2.0"
description = "Bindings for exchanging OAuth 2 tokens"
repository = "https://github.com/alexcrichton/oauth2-rs"

[dependencies]
curl = "0.4.0"
url = "1.0"
log = "0.3"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"

[dev-dependencies]
mockito = "0.8.1"
