[package]
name = "oauth2"
authors = ["Alex Crichton <alex@alexcrichton.com>", "Florin Lipan <florinlipan@gmail.com>", "David A. Ramos <ramos@cs.stanford.edu>"]
version = "3.0.0-alpha.9"
license = "MIT/Apache-2.0"
description = "An extensible, strongly-typed implementation of OAuth2"
repository = "https://github.com/ramosbugs/oauth2-rs"
edition = "2018"
readme = "README.md"

[package.metadata.docs.rs]
all-features = true

[badges]
maintenance = { status = "actively-developed" }

[features]
default = ["reqwest-09"]
futures-01 = ["futures-0-1"]
futures-03 = ["futures-0-3", "async-trait"]
reqwest-09 = ["reqwest-0-9"]
reqwest-010 = ["reqwest-0-10"]

[dependencies]
async-trait = { version = "0.1", optional = true }
base64 = "0.10"
curl = { version = "0.4.0", optional = true }
failure = "0.1"
failure_derive = "0.1"
futures-0-1 = { version = "0.1", optional = true, package = "futures" }
futures-0-3 = { version = "0.3", optional = true, package = "futures" }
http = "0.1"
rand = "0.6"
reqwest-0-9 = { version = "0.9", optional = true, package = "reqwest" }
reqwest-0-10 = { version = "=0.10.0-alpha.2", optional = true, features = ["blocking"], package = "reqwest" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.7"
# To support rustc < 1.36
unicode-normalization = "=0.1.9"
url = "2.1"

[dev-dependencies]
hex = "0.4.0"
rust-crypto = "0.2.36"
tokio = "0.1"
uuid = { version = "0.8.1", features = ["v4"] }
