[package]
name = "oauth2"
authors = ["Alex Crichton <alex@alexcrichton.com>", "Florin Lipan <florinlipan@gmail.com>", "David A. Ramos <ramos@cs.stanford.edu>"]
version = "3.0.0-alpha.4"
license = "MIT/Apache-2.0"
description = "Bindings for exchanging OAuth 2 tokens"
repository = "https://github.com/ramosbugs/oauth2-rs"

[features]
default = ["reqwest"]

[dependencies]
base64 = "0.9"
curl = { version = "0.4.0", optional = true }
failure = "0.1"
failure_derive = "0.1"
futures = "0.1"
http = "0.1"
rand = "0.6"
reqwest = { version = "0.9", optional = true }
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
sha2 = "0.7"
tokio-io = "0.1"
url = "2.1"

[dev-dependencies]
tokio = "0.1"
